# Generated by Django 2.1.3 on 2019-03-16 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('post_date', models.DateTimeField()),
                ('post_body', models.TextField()),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
